# # print("Welcome to", end="   *   ")
# # print("IT News", end='   가   ')
# # print("Web site")
# print("안녕하세요")
# print(123)
# print("지금 당장 바로")
# print()
# print("도전하세요\n기회는 chance")
# print()
# print("1등 상금은 100000000원이며")
# print()
# print("2등에게는 10000*100원이 증정됩니다")
# print()
# print("그 금액은 바로\t한화",10000*100,"원입니다") 